### ISSUE TITLE
Can't get "connection lost" alert to go away once it starts

### ISSUE THREAD

**Issue by uusijani** [gonimo/gonimo#15]
I'm testing Gonimo in anticipation of real-word deployment, and so far everything else seems to work as expected, but for some reason I can't get the "connection lost" alert to go away once it starts, even after the connection is re-established (as indicated by the video stream resuming). The red overlay (with "connection lost!") keeps flashing over the video stream, and the alarm sound keeps ringing no matter what I do in-tab. The only workaround I've come up with is refreshing the tab (F5).

In case this is environment-related, my laptop has Ubuntu 20.04 with Chrome 80.0.3987.116, my Android phone has Chrome 80.0.3987.119, and I've tested both ways (both as either the baby or the parent). I haven't tested the Android app yet to see if it's any different.

**Comment by eskimor** [comment]
Thanks @uusijani ! If there is an alarm, either video or audio is not working - if both work fine but the alarm is still there.

Could you verify that audio is working as well (not just video?)? Other than that, if it does not recover by itself, does stopping the connection and re-connecting work for you?

**Comment by uusijani** [comment]
Thanks for taking a look, @eskimor  (and thanks for the lightning-speed response!)

So yes, both the video and the audio seem to be streaming when this occurs. (I should note though, that my confirmation here is based on the visual audio level indicator. I'll try to confirm the actual audio once my testing environment allows for testing noises loud enough to hear from under the alarm sound.)

I came up with the following steps to reproduce the issue (with fixed phone and laptop roles just for simplicity):

1. Start baby (on the phone)
2. Start parent (on the laptop) and connect to baby (so far so good)
3. Disconnect phone (baby) from network to cause the parent (the laptop) to show the alarm
4. Reconnect phone (baby) to network
5. The stream (on parent, laptop) does not come back, alarm remains
6. From parent (laptop), select Home, respond "OK" to "Are you sure"
7. Still on parent (laptop), reconnect to baby

After this, the stream (with audio) is playing (on the laptop) underneath the red warning overlay. The alarm sound has been playing non-stop since step 3.

I'm unsure if the stream is supposed to come back to life by itself at step 5 or not, but either way, with my current setup it doesn't (that is, it remains frozen). That's the reason for steps 6-7: to get the stream showing again.

**Comment by eskimor** [comment]
Thanks for the detailed reproduction steps: That sounds bad! I'll try to reproduce and fix the issue asap.

**Comment by eskimor** [comment]
I can reproduce this. Very weird, I hope to be able to fix this soon.

**Comment by eskimor** [comment]
Thanks a lot for reporting this!

**Comment by uusijani** [comment]
Cool! And thanks again, very impressed with the product otherwise 👍

**Comment by eskimor** [comment]
I fixed the problem locally, but I am having some problems with the deployment. Should have something working online this week.

**Comment by eskimor** [comment]
Fixed in production.

**Comment by eskimor** [comment]
Oh boy: https://github.com/w3c/webrtc-pc/issues/1020

**Comment by eskimor** [comment]
Fixed on production. Please have a look @uusijani :-)

**Comment by arkonbob** [comment]
I confirm this is now fixed. Also the recent oddity where "connection lost" audio starts playing whenever a session is ended, until the browser is refreshed, seems to have been fixed too.

**Comment by eskimor** [comment]
Thanks!

**Comment by uusijani** [comment]
Confirming as fixed! (Sorry for not getting back sooner, looks like Github failed to notify me.)
