### ISSUE TITLE
Where is the app from PlayStore?

### ISSUE THREAD

**Issue by danbruegge** [gonimo/gonimo#18]
On the weekend we needed the app on another phone but weren't able to find it in the playstore anymore.

What happened?

**Comment by eskimor** [comment]
Hi @danbruegge! It broke unfortunately due to a browser upgrade and we have not yet been able to fix it. Therefore I decided to remove it from the store so people won't pay for a broken app. We are sorry about that. The web app has been fixed though and should work fine.

**Comment by danbruegge** [comment]
@eskimor - thanks for the info. Hope it will be back soon. :)
