### ISSUE TITLE
app.gonimo.com ssl certificate expired

### ISSUE THREAD

**Issue by lovegandhi** [gonimo/gonimo#21]
The title says it all. Let's Encrypt certificate has expired on Feb 20, 2021

PS: thanks for this awesome app!

**Comment by eskimor** [comment]
Shoot, thanks for the report!

**Comment by lovegandhi** [comment]
@eskimor No auto renewal for cert expiration? The cert has expired once again.

**Comment by eskimor** [comment]
We do have auto renewal, but it broke for some reason. Anyhow, thanks - I will look into that.
