### ISSUE TITLE
Android app does not keep screen on

### ISSUE THREAD

**Issue by cdhowie** [gonimo/gonimo#8]
When acting as a parent or baby station, the Android app does not keep the screen on.  This causes the app to stop working after the screen timeout.  (Android 9, Pixel 3)

**Comment by eskimor** [comment]
Thanks a lot for getting in touch here - Android reviews don't really allow for a conversation. I am already working on upgrading to the latest Android SDK, so we can finally implement a proper foreground service, which would fix this and also other (less severe) issues.

Unfortunately the upgrade has proven to be a bit involved, but I hope to have a fix ready soon!

Does at least the browser version work for you or is it completely doomed?

**Comment by eskimor** [comment]
Ok, I just checked. What I can do apart from trying to fix this asap is to refund you. But apparently I need your [email address](https://support.google.com/googleplay/android-developer/answer/2741495?hl=en) for doing that. If you are interested shoot me a message on hello @ gonimo.com . Sorry again for the inconvenience!

**Comment by cdhowie** [comment]
> Unfortunately the upgrade has proven to be a bit involved, but I hope to have a fix ready soon!

I certainly understand. One of my responsibilities at my job is Android development. If there's any tasks that are somewhat easy to delegate, I'd be happy to take a look and see if I can help.

> Does at least the browser version work for you or is it completely doomed?

It works well enough.  On an older phone (Galaxy S4) as a parent station, having the screen off does not appear to affect the audio stream.  On my phone I just use an [Automate](https://play.google.com/store/apps/details?id=com.llamalab.automate) flow to keep the screen on.  If I have my laptop handy, I sometimes just use the web app from there since it doesn't suffer this limitation.

> Can I ping you here, once I have something that should work?

Of course, I'd be happy to help test.

> What I can do apart from trying to fix this asap is to refund you.

That's not necessary at all, but I appreciate the offer.  I still use the app regularly.

**Comment by eskimor** [comment]
Thanks a lot! Unfortunately at the moment there are not really any tasks I could delegate - buuut when I get to implementing the foreground service I might actually have a question or two. I remember something about notifications being quite weird.

Really glad Gonimo is not completely useless for you in the meantime!

**Comment by eskimor** [comment]
Status update: Development build is already mostly working again. Next step, fix remaining issues and make Android build work - then finally foreground service. *phew*

**Comment by eskimor** [comment]
Boy this took long, but we are almost there. I have it working on my phone! :-) Needs a bit more polishing and testing and I need to figure out why the app size exploded from 8 MB to 30 MB, but other than that things are looking good! :-)

**Comment by eskimor** [comment]
I should be able to deliver at least a beta version to the play store  this week.

**Comment by eskimor** [comment]
Beta is online. App size increased quite a bit, hopefully that will be resolved soon too. But it should make Android 9 work smoothly. (Screen gets switched off, but Gonimo should continue to work as expected.)

**Comment by eskimor** [comment]
@cdhowie On the beta channel the update is finally live (took Google over 24 hours), could you have a look whether it resolves your issue? Thanks a lot!

**Comment by cdhowie** [comment]
Yep, I signed up to be a beta tester last night and didn't see the update. Figured it was stuck in the Google pipeline.

I will test over the next few days and let you know how it goes.

**Comment by eskimor** [comment]
Awesome, thanks! :-)

**Comment by cdhowie** [comment]
Sorry, I forgot to test awhile ago but had an opportunity to recently and am pleased to report that everything worked very well, even in the background.

**Comment by eskimor** [comment]
Awesome, thanks! :-)
